# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

AllCops:
  Exclude:
    - '.git/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'log/**/*'
    - 'public/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'config.ru'
    - 'Rakefile'

StringLiterals:
  EnforcedStyle: single_quotes
Style/FrozenStringLiteralComment:
  Enabled: true
