# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.1.3'

gem 'rails', '~> 7.0.4'

gem 'acts_as_list'
gem 'bootsnap', require: false
gem 'bootstrap'
gem 'bootstrap_form'
gem 'faker'
gem 'google-apis-identitytoolkit_v3', require: false
gem 'importmap-rails'
gem 'mini_racer'
gem 'mysql2'
gem 'puma'
gem 'rails-i18n', '~> 7.0.0'
gem 'sassc-rails'
gem 'sprockets-rails'
gem 'stimulus-rails'
gem 'turbo-rails'

group :development, :test do
  gem 'debug'
  gem 'factory_bot_rails'
  gem 'rspec-rails'
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
end

group :development do
  gem 'web-console'
end

group :test do
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
end
