# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.1.3'

gem 'rails', '~> 7.0.4'

gem 'bootsnap', require: false
gem 'importmap-rails'
gem 'mysql2'
gem 'puma'
gem 'sassc-rails'
gem 'sprockets-rails'
gem 'stimulus-rails'
gem 'turbo-rails'

group :development, :test do
  gem 'debug'
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
end

group :development do
  gem 'web-console'
end
